apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
    app: demo-app
spec:
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
        app: demo-app
        type: front-end
    spec:
      containers:
        - name: resultapp-container
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      name: result-pod
      app: demo-app
      type: front-end