apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    name: result-pod
    app: demo-app
    type: front-end
spec:
  containers:
    - name: resultapp-container
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80