apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app-deployment
    app: demo-app
spec:
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
        app: demo-app
        type: front-end
    spec:
      containers:
        - name: votingapp-container
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      name: voting-pod
      app: demo-app
      type: front-end