apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: demo-app
spec:
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-app
        type: backend
    spec:
      containers:
        - name: worker-container
          image: dockersamples/examplevotingapp_worker
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: demo-app
      type: backend