apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: demo-app
    type: backend
spec:
  containers:
    - name: worker-container
      image: dockersamples/examplevotingapp_worker
